mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_DATABASE=spring_boot_user
    - MYSQL_ROOT_PASSWORD=
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"